# https://medium.com/better-programming/dockerizing-react-app-and-express-api-with-mongodb-f3a06bebf570

version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: Backend 
    
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    container_name: Frontend 

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongoDb