FROM node:12-alpine as builder
WORKDIR /app
COPY package.json /app/package.json
RUN apk --no-cache add --virtual builds-deps build-base python
RUN npm install
RUN npm install -D nodemon
COPY . /app
RUN npm install -g nodemon

EXPOSE 3000
CMD [ "npm", "start" ]
# FROM node:12-alpine
# WORKDIR /app
# COPY --from=builder /app/dist /app
# COPY package.json /app/package.json
# RUN apk --no-cache add --virtual builds-deps build-base python
# RUN npm install --only=prod

# EXPOSE 8080 
# USER node
# CMD ["node", "index.js"]